"""Database tables (SECURITY.md §3, §12, §16).

Three things are structural here and should not be worked around later:

* **Tenancy.** Every table that holds user data carries ``tenant_id`` and is
  protected by row-level security. The policies are in the migration, because they
  are database objects, not ORM metadata; this module records which tables they
  must cover (:data:`TENANT_SCOPED_TABLES`) and a test asserts the two agree.
* **S2 columns hold ciphertext only.** They are ``bytea``, named ``*_ciphertext``,
  and are written and read through :mod:`aria_core.crypto.envelope`, never
  directly. The row's id is part of the AES-GCM associated data, so a ciphertext
  cannot be moved to another row or another tenant and still decrypt.
* **The audit table is append-only.** No ORM code may update or delete it, and the
  migration revokes those rights from the application role as well.
"""

from __future__ import annotations

import datetime as dt
import decimal
import uuid
from typing import Any

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    LargeBinary,
    MetaData,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from aria_core.schemas.identity import new_id
from aria_core.sensitivity import Sensitivity
from aria_core.state_machines.application import ApplicationState

__all__ = [
    "TENANT_SCOPED_TABLES",
    "Application",
    "AuditEvent",
    "Base",
    "ConsumedApplyTaskJti",
    "LlmRequest",
    "SensitiveProfile",
    "Tenant",
    "TenantDataKey",
    "User",
]

#: Explicit naming so constraints and indexes are stable across autogenerated
#: migrations and can be referenced by name in DDL.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {  # noqa: RUF012  (SQLAlchemy reads this as a plain dict)
        dict[str, Any]: JSONB,
        decimal.Decimal: Numeric(12, 6),
    }


def _uuid_pk() -> Mapped[uuid.UUID]:
    return mapped_column(UUID(as_uuid=True), primary_key=True, default=new_id)


def _created_at() -> Mapped[dt.datetime]:
    return mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())


class Tenant(Base):
    """One customer account. The founder is tenant #1; nothing is special about it."""

    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = _uuid_pk()
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    created_at: Mapped[dt.datetime] = _created_at()


class User(Base):
    """A person inside a tenant. S1: name and email are personal, not sensitive."""

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = _uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False
    )
    email: Mapped[str] = mapped_column(String(320), nullable=False)
    display_name: Mapped[str] = mapped_column(String(200), nullable=False)
    created_at: Mapped[dt.datetime] = _created_at()

    __table_args__ = (UniqueConstraint("tenant_id", "email"),)


class TenantDataKey(Base):
    """A tenant's data encryption key, wrapped by the KMS root key.

    Only the wrapped form is stored. Unwrapping happens in memory for the duration
    of one operation (SECURITY.md §10). Rotation adds a new version; old versions
    stay so existing ciphertext remains readable.
    """

    __tablename__ = "tenant_data_keys"

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), primary_key=True
    )
    key_version: Mapped[int] = mapped_column(primary_key=True)
    wrapped_dek: Mapped[bytes] = mapped_column(
        LargeBinary,
        nullable=False,
        info={"sensitivity": Sensitivity.S3, "accessor": "aria_core.crypto.data_keys"},
    )
    #: Which KMS key wrapped it, so a rotated root key can still unwrap old DEKs.
    kms_key_id: Mapped[str] = mapped_column(String(200), nullable=False)
    created_at: Mapped[dt.datetime] = _created_at()
    retired_at: Mapped[dt.datetime | None] = mapped_column(DateTime(timezone=True))


class SensitiveProfile(Base):
    """S2 answers, encrypted per tenant (SECURITY.md §3).

    Exists in Phase 0 to prove the S2 path end to end: nothing writes plaintext,
    the ciphertext is bound to this row, and no code path can send these values to
    a model or a log line. The real onboarding fields arrive in Phase 1.
    """

    __tablename__ = "sensitive_profile"

    id: Mapped[uuid.UUID] = _uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    #: Which tenant data key version these ciphertexts were written with.
    key_version: Mapped[int] = mapped_column(nullable=False)
    work_authorization_ciphertext: Mapped[bytes | None] = mapped_column(
        LargeBinary, info={"sensitivity": Sensitivity.S2, "accessor": "aria_core.db.sensitive_profile"}
    )
    eeo_answers_ciphertext: Mapped[bytes | None] = mapped_column(
        LargeBinary, info={"sensitivity": Sensitivity.S2, "accessor": "aria_core.db.sensitive_profile"}
    )
    created_at: Mapped[dt.datetime] = _created_at()
    updated_at: Mapped[dt.datetime] = _created_at()

    __table_args__ = (UniqueConstraint("user_id"),)


class Application(Base):
    """One application, minimal in Phase 0.

    It exists so row-level security and the state machine have something real to
    act on. Phase 3 and Phase 5 add the posting, resume artifact and receipt
    columns.
    """

    __tablename__ = "applications"

    id: Mapped[uuid.UUID] = _uuid_pk()
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False
    )
    #: Stable reference to the posting. Becomes a foreign key in Phase 3.
    job_ref: Mapped[str] = mapped_column(String(500), nullable=False)
    state: Mapped[str] = mapped_column(String(40), nullable=False)
    created_at: Mapped[dt.datetime] = _created_at()
    updated_at: Mapped[dt.datetime] = _created_at()

    __table_args__ = (
        CheckConstraint(
            "state IN (" + ", ".join(f"'{state.value}'" for state in ApplicationState) + ")",
            name="state_is_known",
        ),
        Index("ix_applications_tenant_id_state", "tenant_id", "state"),
    )


class AuditEvent(Base):
    """One link in a hash chain (SECURITY.md §16).

    Append-only and tamper-evident: each row carries the hash of the previous row
    in its chain, so removing or editing a row breaks verification. Writes to one
    chain are serialized, so ``seq`` has no gaps and no two rows claim the same
    predecessor.

    ``chain_id`` is the tenant's id for tenant events, and the nil UUID for
    platform events (service start-up, cross-tenant denials, admin actions), which
    a tenant-scoped session can never see. ``tenant_id`` is NULL exactly for
    platform events; the RLS policies rely on that.

    ``payload`` holds S0/S1 data only. The writer rejects anything stricter.
    """

    __tablename__ = "audit_events"

    id: Mapped[uuid.UUID] = _uuid_pk()
    chain_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    seq: Mapped[int] = mapped_column(BigInteger, nullable=False)
    prev_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    hash: Mapped[str] = mapped_column(String(64), nullable=False)
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True))

    occurred_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    actor_kind: Mapped[str] = mapped_column(String(40), nullable=False)
    actor_id: Mapped[str] = mapped_column(String(200), nullable=False)
    action: Mapped[str] = mapped_column(String(80), nullable=False)
    subject_kind: Mapped[str] = mapped_column(String(40), nullable=False)
    subject_id: Mapped[str] = mapped_column(String(200), nullable=False)
    outcome: Mapped[str] = mapped_column(String(20), nullable=False)
    reason: Mapped[str] = mapped_column(Text, nullable=False, default="")
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)

    __table_args__ = (
        UniqueConstraint("chain_id", "seq"),
        UniqueConstraint("hash"),
        CheckConstraint(
            "(chain_id = '00000000-0000-0000-0000-000000000000'::uuid) = (tenant_id IS NULL)",
            name="platform_chain_has_no_tenant",
        ),
        CheckConstraint("outcome IN ('allowed', 'denied', 'ok', 'failed')", name="outcome_is_known"),
        Index("ix_audit_events_chain_id_seq", "chain_id", "seq"),
    )


class LlmRequest(Base):
    """Metadata for one request through the gateway (SECURITY.md §13).

    Deliberately no prompt, no completion and no untrusted content: the gateway
    logs what a request cost and what it was for, not what it said.
    """

    __tablename__ = "llm_requests"

    id: Mapped[uuid.UUID] = _uuid_pk()
    #: Never null: every request is made on behalf of one tenant, including the
    #: ones the gateway refuses, so spend and refusals are always attributable.
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False
    )
    purpose: Mapped[str] = mapped_column(String(80), nullable=False)
    provider: Mapped[str] = mapped_column(String(40), nullable=False)
    model: Mapped[str] = mapped_column(String(120), nullable=False)
    prompt_tokens: Mapped[int] = mapped_column(default=0)
    completion_tokens: Mapped[int] = mapped_column(default=0)
    cost_usd: Mapped[decimal.Decimal] = mapped_column(Numeric(12, 6), default=decimal.Decimal(0))
    outcome: Mapped[str] = mapped_column(String(20), nullable=False)
    #: Set when the gateway refused to dispatch, e.g. "s2_field:work_authorization".
    refusal_reason: Mapped[str | None] = mapped_column(String(200))
    created_at: Mapped[dt.datetime] = _created_at()

    __table_args__ = (Index("ix_llm_requests_tenant_id_created_at", "tenant_id", "created_at"),)


class ConsumedApplyTaskJti(Base):
    """Spent ApplyTask identifiers, so a captured task cannot be replayed.

    One row per task the Runner has acted on. The unique primary key is the whole
    mechanism: a second attempt to insert the same ``jti`` fails. Rows are pruned
    after ``expires_at``, since an expired task is refused by the signature check
    anyway.
    """

    __tablename__ = "consumed_apply_task_jtis"

    jti: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False
    )
    application_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    consumed_at: Mapped[dt.datetime] = _created_at()
    expires_at: Mapped[dt.datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    __table_args__ = (Index("ix_consumed_apply_task_jtis_expires_at", "expires_at"),)


#: Columns holding S2 or S3 data carry their class and their one legitimate accessor
#: module in ``info``:
#:
#:     info={"sensitivity": Sensitivity.S2, "accessor": "aria_core.db.sensitive_profile"}
#:
#: ``test_architecture_s2.py`` reads these markers and fails if such a column is
#: mapped as anything but binary, if a ``*_ciphertext`` column is unmarked, or if any
#: module other than its declared accessor so much as mentions it. The encryption is
#: only as good as the number of places that can bypass it.


#: Tables whose rows belong to exactly one tenant and must therefore be covered by
#: a row-level security policy. ``tenants`` is scoped by its own ``id`` and
#: ``audit_events`` additionally carries the platform chain, so both are listed
#: separately in the migration. Kept here so
#: ``test_rls_cross_tenant.py::test_every_tenant_table_has_row_security`` can
#: compare intent with what the database actually enforces.
TENANT_SCOPED_TABLES: frozenset[str] = frozenset(
    {
        "tenants",
        "users",
        "tenant_data_keys",
        "sensitive_profile",
        "applications",
        "audit_events",
        "llm_requests",
        "consumed_apply_task_jtis",
    }
)
